In [1]:
import pandas as pd

In [5]:
pd.read_csv('/home/bhanselman/bhanselman/asymmetry_plots/modified_tests/bank1_doppler_1e28_snrs.csv')

    Frequency        SNR  SNR_Modified     Factor
0        9050  11.203095     60.761050   5.423595
1        9150   9.571206     44.644952   4.664506
2        9250  10.911859     34.598541   3.170728
3        9350   8.611578     18.306069   2.125751
4        9450   8.268256     51.842839   6.270106
5        9550   5.545657     33.774673   6.090292
6        9650   7.684197     36.273709   4.720560
7        9750   5.432018     61.936156  11.402054
8        9850   8.313200     43.825903   5.271845
9        9950  10.734347     51.932443   4.837970
10      10050   6.002393     13.374917   2.228264

In [6]:
pd.read_csv('/home/bhanselman/bhanselman/asymmetry_plots/modified_tests/bank1_intensity_1e28_snrs.csv')

    Frequency       SNR  SNR_Modified     Factor
0        9050  3.777738     10.900179   2.885372
1        9150  5.019078     11.969561   2.384813
2        9250  5.568415     19.442575   3.491581
3        9350  3.650366      7.893128   2.162284
4        9450  3.832989     18.655410   4.867066
5        9550  3.247363     15.700265   4.834773
6        9650  1.468492     15.764313  10.735032
7        9750  2.497659     14.602460   5.846459
8        9850  4.376834      9.744992   2.226493
9        9950  5.085932      9.793128   1.925533
10      10050  4.559431      7.853490   1.722472